version: '1.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: colqueed
      POSTGRES_PASSWORD: killzone20189
      POSTGRES_DB: Prueba

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
